// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transport.proto

package webfacade

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Http 头封装
type Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HttpRequest struct {
	Url                  string    `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method               string    `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers              []*Header `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte    `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HttpRequest) Reset()         { *m = HttpRequest{} }
func (m *HttpRequest) String() string { return proto.CompactTextString(m) }
func (*HttpRequest) ProtoMessage()    {}
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{1}
}
func (m *HttpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequest.Unmarshal(m, b)
}
func (m *HttpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequest.Marshal(b, m, deterministic)
}
func (m *HttpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequest.Merge(m, src)
}
func (m *HttpRequest) XXX_Size() int {
	return xxx_messageInfo_HttpRequest.Size(m)
}
func (m *HttpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequest proto.InternalMessageInfo

func (m *HttpRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HttpRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HttpRequest) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type HttpResponse struct {
	StatusCode           int64     `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers              []*Header `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	ContentType          string    `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Body                 []byte    `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HttpResponse) Reset()         { *m = HttpResponse{} }
func (m *HttpResponse) String() string { return proto.CompactTextString(m) }
func (*HttpResponse) ProtoMessage()    {}
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{2}
}
func (m *HttpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResponse.Unmarshal(m, b)
}
func (m *HttpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResponse.Marshal(b, m, deterministic)
}
func (m *HttpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResponse.Merge(m, src)
}
func (m *HttpResponse) XXX_Size() int {
	return xxx_messageInfo_HttpResponse.Size(m)
}
func (m *HttpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResponse proto.InternalMessageInfo

func (m *HttpResponse) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *HttpResponse) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpResponse) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *HttpResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type PBResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            int64    `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success              bool     `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBResponse) Reset()         { *m = PBResponse{} }
func (m *PBResponse) String() string { return proto.CompactTextString(m) }
func (*PBResponse) ProtoMessage()    {}
func (*PBResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{3}
}
func (m *PBResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBResponse.Unmarshal(m, b)
}
func (m *PBResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBResponse.Marshal(b, m, deterministic)
}
func (m *PBResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBResponse.Merge(m, src)
}
func (m *PBResponse) XXX_Size() int {
	return xxx_messageInfo_PBResponse.Size(m)
}
func (m *PBResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PBResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PBResponse proto.InternalMessageInfo

func (m *PBResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PBResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PBResponse) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *PBResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PBResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type PBBody struct {
	Payload              map[string]*types.Any `protobuf:"bytes,1,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PBBody) Reset()         { *m = PBBody{} }
func (m *PBBody) String() string { return proto.CompactTextString(m) }
func (*PBBody) ProtoMessage()    {}
func (*PBBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{4}
}
func (m *PBBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBBody.Unmarshal(m, b)
}
func (m *PBBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBBody.Marshal(b, m, deterministic)
}
func (m *PBBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBBody.Merge(m, src)
}
func (m *PBBody) XXX_Size() int {
	return xxx_messageInfo_PBBody.Size(m)
}
func (m *PBBody) XXX_DiscardUnknown() {
	xxx_messageInfo_PBBody.DiscardUnknown(m)
}

var xxx_messageInfo_PBBody proto.InternalMessageInfo

func (m *PBBody) GetPayload() map[string]*types.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "coomons.webfacade.Header")
	proto.RegisterType((*HttpRequest)(nil), "coomons.webfacade.HttpRequest")
	proto.RegisterType((*HttpResponse)(nil), "coomons.webfacade.HttpResponse")
	proto.RegisterType((*PBResponse)(nil), "coomons.webfacade.PBResponse")
	proto.RegisterType((*PBBody)(nil), "coomons.webfacade.PBBody")
	proto.RegisterMapType((map[string]*types.Any)(nil), "coomons.webfacade.PBBody.PayloadEntry")
}

func init() { proto.RegisterFile("transport.proto", fileDescriptor_a97e32c760ec1b28) }

var fileDescriptor_a97e32c760ec1b28 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x95, 0x9b, 0x6e, 0x97, 0x4e, 0x2a, 0x01, 0xd6, 0x0a, 0x65, 0x57, 0x42, 0x94, 0x1e, 0x50,
	0xc5, 0xc1, 0x8b, 0x76, 0x2f, 0x88, 0x13, 0x14, 0x21, 0x2d, 0xb7, 0x28, 0xe2, 0xc4, 0xa5, 0x72,
	0xe2, 0xd9, 0x2e, 0x22, 0xf5, 0x04, 0xdb, 0x01, 0xf9, 0xc6, 0x0f, 0xf0, 0x05, 0xf0, 0xb1, 0x28,
	0x76, 0x52, 0x22, 0xd1, 0xc3, 0xde, 0xe6, 0x8d, 0xdf, 0xe4, 0xbd, 0x3c, 0x3d, 0x78, 0xe8, 0x8c,
	0xd4, 0xb6, 0x21, 0xe3, 0x44, 0x63, 0xc8, 0x11, 0x7f, 0x5c, 0x11, 0xed, 0x49, 0x5b, 0xf1, 0x03,
	0xcb, 0x5b, 0x59, 0x49, 0x85, 0x17, 0xe7, 0x3b, 0xa2, 0x5d, 0x8d, 0x97, 0x81, 0x50, 0xb6, 0xb7,
	0x97, 0x52, 0xfb, 0xc8, 0x5e, 0xbd, 0x82, 0xd9, 0x0d, 0x4a, 0x85, 0x86, 0x3f, 0x82, 0xe4, 0x2b,
	0xfa, 0x8c, 0x2d, 0xd9, 0x7a, 0x5e, 0x74, 0x23, 0x3f, 0x83, 0x93, 0xef, 0xb2, 0x6e, 0x31, 0x9b,
	0x84, 0x5d, 0x04, 0xab, 0x9f, 0x0c, 0xd2, 0x1b, 0xe7, 0x9a, 0x02, 0xbf, 0xb5, 0x68, 0x5d, 0x77,
	0xd7, 0x9a, 0x7a, 0xb8, 0x6b, 0x4d, 0xcd, 0x9f, 0xc0, 0x6c, 0x8f, 0xee, 0x8e, 0x54, 0x7f, 0xd8,
	0x23, 0x7e, 0x0d, 0xa7, 0x77, 0x41, 0xcb, 0x66, 0xc9, 0x32, 0x59, 0xa7, 0x57, 0xe7, 0xe2, 0x3f,
	0xaf, 0x22, 0xba, 0x29, 0x06, 0x26, 0xe7, 0x30, 0x2d, 0x49, 0xf9, 0x6c, 0xba, 0x64, 0xeb, 0x45,
	0x11, 0xe6, 0xd5, 0x6f, 0x06, 0x8b, 0x68, 0xc1, 0x36, 0xa4, 0x2d, 0xf2, 0x67, 0x90, 0x5a, 0x27,
	0x5d, 0x6b, 0xb7, 0x15, 0x29, 0x0c, 0x5e, 0x92, 0x02, 0xe2, 0xea, 0x3d, 0x29, 0x1c, 0x4b, 0x4f,
	0xee, 0x2d, 0xfd, 0x1c, 0x16, 0x15, 0x69, 0x87, 0xda, 0x6d, 0x9d, 0x6f, 0x30, 0x4b, 0xc2, 0xdf,
	0xa4, 0xfd, 0xee, 0x93, 0x6f, 0xf0, 0xa8, 0xbb, 0x5f, 0x0c, 0x20, 0xdf, 0x1c, 0xbc, 0x71, 0x98,
	0x8e, 0x4c, 0x85, 0x99, 0x67, 0x70, 0xba, 0x47, 0x6b, 0xe5, 0x6e, 0xc8, 0x76, 0x80, 0xfc, 0x29,
	0x80, 0x89, 0xc1, 0x6e, 0xbf, 0xa8, 0xa0, 0x98, 0x14, 0xf3, 0x7e, 0xf3, 0x51, 0x75, 0x87, 0xb6,
	0xad, 0x2a, 0xb4, 0x36, 0x48, 0x3e, 0x28, 0x06, 0xd8, 0xbd, 0x34, 0xd2, 0xd7, 0x24, 0x55, 0x76,
	0x12, 0xcc, 0x0c, 0x70, 0xf5, 0x87, 0xc1, 0x2c, 0xdf, 0x6c, 0x48, 0x79, 0xfe, 0xf6, 0x1f, 0x89,
	0x85, 0x18, 0x5e, 0x1c, 0x89, 0x21, 0x72, 0x45, 0x1e, 0x89, 0x1f, 0xb4, 0x33, 0xfe, 0xf0, 0xb1,
	0x8b, 0x1c, 0x16, 0xe3, 0x87, 0x23, 0xad, 0x79, 0x39, 0x6e, 0x4d, 0x7a, 0x75, 0x26, 0x62, 0xf9,
	0xc4, 0x50, 0x3e, 0xf1, 0x4e, 0xfb, 0xbe, 0x4b, 0x6f, 0x26, 0xaf, 0xd9, 0x26, 0xfd, 0x3c, 0x3f,
	0x68, 0x97, 0xb3, 0xc0, 0xba, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xab, 0x8c, 0x09, 0x8a, 0xd6,
	0x02, 0x00, 0x00,
}
