// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: model.proto

package models

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 错误定义
type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode            int64    `protobuf:"varint,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 分页查询
type PageQuery struct {
	LastId               int64    `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
	PageNumber           int64    `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	ReturnTotal          bool     `protobuf:"varint,4,opt,name=return_total,json=returnTotal,proto3" json:"return_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageQuery) Reset()         { *m = PageQuery{} }
func (m *PageQuery) String() string { return proto.CompactTextString(m) }
func (*PageQuery) ProtoMessage()    {}
func (*PageQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}
func (m *PageQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageQuery.Unmarshal(m, b)
}
func (m *PageQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageQuery.Marshal(b, m, deterministic)
}
func (m *PageQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageQuery.Merge(m, src)
}
func (m *PageQuery) XXX_Size() int {
	return xxx_messageInfo_PageQuery.Size(m)
}
func (m *PageQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PageQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PageQuery proto.InternalMessageInfo

func (m *PageQuery) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *PageQuery) GetPageNumber() int64 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *PageQuery) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageQuery) GetReturnTotal() bool {
	if m != nil {
		return m.ReturnTotal
	}
	return false
}

type PayloadRequest struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayloadRequest) Reset()         { *m = PayloadRequest{} }
func (m *PayloadRequest) String() string { return proto.CompactTextString(m) }
func (*PayloadRequest) ProtoMessage()    {}
func (*PayloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}
func (m *PayloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadRequest.Unmarshal(m, b)
}
func (m *PayloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadRequest.Marshal(b, m, deterministic)
}
func (m *PayloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadRequest.Merge(m, src)
}
func (m *PayloadRequest) XXX_Size() int {
	return xxx_messageInfo_PayloadRequest.Size(m)
}
func (m *PayloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadRequest proto.InternalMessageInfo

func (m *PayloadRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// 通用Respose
type PayloadResponse struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayloadResponse) Reset()         { *m = PayloadResponse{} }
func (m *PayloadResponse) String() string { return proto.CompactTextString(m) }
func (*PayloadResponse) ProtoMessage()    {}
func (*PayloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}
func (m *PayloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadResponse.Unmarshal(m, b)
}
func (m *PayloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadResponse.Marshal(b, m, deterministic)
}
func (m *PayloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadResponse.Merge(m, src)
}
func (m *PayloadResponse) XXX_Size() int {
	return xxx_messageInfo_PayloadResponse.Size(m)
}
func (m *PayloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadResponse proto.InternalMessageInfo

func (m *PayloadResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *PayloadResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CacheSingle struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Exp                  int64    `protobuf:"varint,2,opt,name=Exp,proto3" json:"Exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheSingle) Reset()         { *m = CacheSingle{} }
func (m *CacheSingle) String() string { return proto.CompactTextString(m) }
func (*CacheSingle) ProtoMessage()    {}
func (*CacheSingle) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}
func (m *CacheSingle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheSingle.Unmarshal(m, b)
}
func (m *CacheSingle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheSingle.Marshal(b, m, deterministic)
}
func (m *CacheSingle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheSingle.Merge(m, src)
}
func (m *CacheSingle) XXX_Size() int {
	return xxx_messageInfo_CacheSingle.Size(m)
}
func (m *CacheSingle) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheSingle.DiscardUnknown(m)
}

var xxx_messageInfo_CacheSingle proto.InternalMessageInfo

func (m *CacheSingle) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CacheSingle) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

type CacheRepeated struct {
	Datas                [][]byte `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"`
	Exp                  int64    `protobuf:"varint,2,opt,name=Exp,proto3" json:"Exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheRepeated) Reset()         { *m = CacheRepeated{} }
func (m *CacheRepeated) String() string { return proto.CompactTextString(m) }
func (*CacheRepeated) ProtoMessage()    {}
func (*CacheRepeated) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}
func (m *CacheRepeated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheRepeated.Unmarshal(m, b)
}
func (m *CacheRepeated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheRepeated.Marshal(b, m, deterministic)
}
func (m *CacheRepeated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheRepeated.Merge(m, src)
}
func (m *CacheRepeated) XXX_Size() int {
	return xxx_messageInfo_CacheRepeated.Size(m)
}
func (m *CacheRepeated) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheRepeated.DiscardUnknown(m)
}

var xxx_messageInfo_CacheRepeated proto.InternalMessageInfo

func (m *CacheRepeated) GetDatas() [][]byte {
	if m != nil {
		return m.Datas
	}
	return nil
}

func (m *CacheRepeated) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Error)(nil), "commons.model.Error")
	proto.RegisterType((*PageQuery)(nil), "commons.model.PageQuery")
	proto.RegisterType((*PayloadRequest)(nil), "commons.model.PayloadRequest")
	proto.RegisterType((*PayloadResponse)(nil), "commons.model.PayloadResponse")
	proto.RegisterType((*CacheSingle)(nil), "commons.model.CacheSingle")
	proto.RegisterType((*CacheRepeated)(nil), "commons.model.CacheRepeated")
	proto.RegisterType((*Empty)(nil), "commons.model.Empty")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0xd3, 0xcf, 0x49, 0xab, 0x32, 0x14, 0x09, 0x22, 0x12, 0x73, 0x90, 0xe0, 0x21,
	0x07, 0x7b, 0xf0, 0x28, 0x58, 0x7a, 0xf0, 0x22, 0x75, 0xeb, 0xc9, 0x8b, 0x6c, 0x9b, 0x21, 0x16,
	0x92, 0xec, 0xba, 0xbb, 0x01, 0xeb, 0xd1, 0xbf, 0x5c, 0x76, 0xdb, 0xd4, 0x16, 0xbc, 0xcd, 0xfb,
	0xe5, 0xcd, 0xc7, 0xcb, 0x42, 0x50, 0x8a, 0x8c, 0x8a, 0x54, 0x2a, 0x61, 0x04, 0x8e, 0x56, 0xa2,
	0x2c, 0x45, 0xa5, 0x53, 0x07, 0xe3, 0x07, 0xe8, 0xcc, 0x94, 0x12, 0x0a, 0x43, 0xe8, 0x95, 0xa4,
	0x35, 0xcf, 0x29, 0xf4, 0x22, 0x2f, 0x19, 0xb0, 0x46, 0xe2, 0x25, 0x0c, 0x9c, 0x65, 0x2a, 0x32,
	0x0a, 0x5b, 0x91, 0x97, 0xf8, 0xec, 0x0f, 0xc4, 0x3f, 0x1e, 0x0c, 0xe6, 0x3c, 0xa7, 0x97, 0x9a,
	0xd4, 0x06, 0xcf, 0xa1, 0x5b, 0x70, 0x6d, 0x9e, 0x32, 0x37, 0xc4, 0x67, 0x3b, 0x85, 0x57, 0x00,
	0x92, 0xe7, 0xf4, 0x5c, 0x97, 0x4b, 0x52, 0xa1, 0xef, 0xbe, 0x1d, 0x10, 0xbc, 0x80, 0xbe, 0x55,
	0x8b, 0xf5, 0x77, 0xb3, 0x62, 0xaf, 0xf1, 0x1a, 0x86, 0x8a, 0x4c, 0xad, 0xaa, 0x77, 0x23, 0x0c,
	0x2f, 0xc2, 0x76, 0xe4, 0x25, 0x7d, 0x16, 0x6c, 0xd9, 0xab, 0x45, 0xf1, 0x2d, 0x9c, 0xcc, 0xf9,
	0xa6, 0x10, 0x3c, 0x63, 0xf4, 0x59, 0x93, 0x36, 0x36, 0x8e, 0xdc, 0x12, 0x77, 0xc9, 0x90, 0x35,
	0x32, 0x5e, 0xc0, 0xe9, 0xde, 0xab, 0xa5, 0xa8, 0x34, 0xe1, 0x0d, 0xf8, 0xa4, 0x94, 0x33, 0x06,
	0x77, 0xe3, 0xf4, 0xe8, 0x0f, 0xa5, 0x2e, 0x2a, 0xb3, 0x86, 0xc3, 0xa1, 0xad, 0xe3, 0xa1, 0x13,
	0x08, 0xa6, 0x7c, 0xf5, 0x41, 0x8b, 0x75, 0x95, 0x17, 0x84, 0x08, 0xed, 0x8c, 0x1b, 0xbe, 0x5b,
	0xed, 0x6a, 0x3c, 0x03, 0x7f, 0xf6, 0x25, 0x77, 0xe9, 0x6c, 0x19, 0xdf, 0xc3, 0xc8, 0x35, 0x31,
	0x92, 0xc4, 0x0d, 0x65, 0x38, 0x86, 0x8e, 0xb5, 0xea, 0xd0, 0x8b, 0xfc, 0x64, 0xc8, 0xb6, 0xe2,
	0x9f, 0xc6, 0x1e, 0x74, 0x66, 0xa5, 0x34, 0x9b, 0xc7, 0xfe, 0x5b, 0xd7, 0x1d, 0xa9, 0x97, 0x5d,
	0xf7, 0xba, 0x93, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xde, 0x14, 0xd6, 0xec, 0x01, 0x00,
	0x00,
}
